# Disable IP forwarding (this server doesn't route traffic):
net.ipv4.ip_forward = 0

# Enable TCP SYN cookies (SYN flood protection):
net.ipv4.tcp_syncookies = 1

# Ignore ICMP broadcast pings:
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Ignore bogus ICMP error responses:
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Prevent IP spoofing:
net.ipv4.conf.all.rp_filter = 1
